name: Wake Up Streamlit
on:
  schedule:
    # This runs at 8:00 AM and 8:00 PM UTC (Midnight & Noon PST in the Lower Mainland)
    - cron: '0 8,20 * * *'
  workflow_dispatch: # Allows you to run it manually to test

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit URL
        run: |
          curl -I --max-redirs 2 https://mahipal-zanakat.streamlit.app/ || true
